%Eryn Kelsey-Adkins
%CS 3210
%Prolog
%Dating Database

%to find the perfect match, run perfect_match(A, B)

%facts:
% gender - names were generated from the top 1000 baby names of 2017
% hobby types (outdoor, collecting, foody, arts and crafts, and games)
% hobbies were gathered from lists of common hobbies 

man(liam).
man(noah).
man(william).
man(james).
man(logan).
man(benjamin).
man(mason).
man(elijah).
man(oliver).
man(jacob).
man(lucas).
man(michael).
man(alexander).
man(ethan).
man(daniel).
man(matthew).
man(aiden).
man(henry).
man(joseph).
man(jackson).
man(samuel).
man(sebastian).
man(david).
man(carter).
man(wyatt).
man(jayden).
man(john).
man(owen).
man(dylan).
man(luke).
woman(emma).
woman(olivia).
woman(ava).
woman(isabella).
woman(sophia).
woman(mia).
woman(charlotte).
woman(amelia).
woman(evelyn).
woman(abigail).
woman(harper).
woman(emily).
woman(elizabeth).
woman(avery).
woman(sofia).
woman(ella).
woman(madison).
woman(scarlett).
woman(victoria).
woman(aria).
woman(grace).
woman(chloe).
woman(camila).
woman(penelope).
woman(riley).
woman(layla).
woman(lillian).
woman(nora).
woman(zoey).
woman(mila).
outdoor(hiking). 
outdoor(backpacking). 
outdoor(camping). 
outdoor(hunting). 
outdoor(fishing). 
outdoor(archery). 
outdoor(canoeing). 
outdoor(kayaking). 
outdoor(running). 
collecting(antiquing). 
collecting(coin_collecting). 
collecting(stamp_collecting). 
foody(cooking). 
foody(baking). 
foody(home_brewing). 
foody(mixology). 
arts_crafts(painting). 
arts_crafts(drawing). 
arts_crafts(origami). 
arts_crafts(photography). 
arts_crafts(calligraphy). 
arts_crafts(sewing). 
arts_crafts(knitting). 
arts_crafts(wood_working). 
arts_crafts(metal_working).  
arts_crafts(pottery). 
games(board_games). 
games(puzzles). 
games(cards). 
games(chess). 
games(video_games). 
games(darts). 
games(pool). 

%rules:
% kinsey scale (1 - 6) randomly generated
% age (21 - 45) randomly generated
% personality type (introvert to extrovert on a 1 - 10 scale) randomly generated
% hobbies - randomly generated by type
% a quick thank you to my husband for being my living random number generator
% all numbers were generated through rolling various sided dice

kinsey(liam, 4).
kinsey(noah, 5).
kinsey(william, 3).
kinsey(james, 2).
kinsey(logan, 5).
kinsey(benjamin, 4).
kinsey(mason, 1).
kinsey(elijah, 4).
kinsey(oliver, 2).
kinsey(jacob, 1).
kinsey(lucas, 6).
kinsey(michael, 5).
kinsey(alexander, 2).
kinsey(ethan, 3).
kinsey(daniel, 4).
kinsey(matthew, 6).
kinsey(aiden, 2).
kinsey(henry, 2).
kinsey(joseph, 4).
kinsey(jackson, 4).
kinsey(samuel, 6).
kinsey(sebastian, 3).
kinsey(david, 4).
kinsey(carter, 1).
kinsey(wyatt, 1).
kinsey(jayden, 6).
kinsey(john, 4).
kinsey(owen, 4).
kinsey(dylan, 2).
kinsey(luke, 2).
kinsey(emma, 5).
kinsey(olivia, 3).
kinsey(ava, 1).
kinsey(isabella, 6).
kinsey(sophia, 6).
kinsey(mia, 5).
kinsey(charlotte, 6).
kinsey(amelia, 2).
kinsey(evelyn, 4).
kinsey(abigail, 6).
kinsey(harper, 2).
kinsey(emily, 2).
kinsey(elizabeth, 1).
kinsey(avery, 1).
kinsey(sofia, 5).
kinsey(ella, 4).
kinsey(madison, 6).
kinsey(scarlett, 4).
kinsey(victoria, 1).
kinsey(aria, 5).
kinsey(grace, 3).
kinsey(chloe, 3).
kinsey(camila, 4).
kinsey(penelope, 4).
kinsey(riley, 5).
kinsey(layla, 2).
kinsey(lillian, 4).
kinsey(nora, 2).
kinsey(zoey, 5).
kinsey(mila, 5).
age(liam, 25).
age(noah, 32).
age(william, 31).
age(james, 39).
age(logan, 27).
age(benjamin, 31).
age(mason, 32).
age(elijah, 34).
age(oliver, 43).
age(jacob, 28).
age(lucas, 23).
age(michael, 21).
age(alexander, 43).
age(ethan, 22).
age(daniel, 28).
age(matthew, 42).
age(aiden, 29).
age(henry, 26).
age(joseph, 32).
age(jackson, 21).
age(samuel, 26).
age(sebastian, 28).
age(david, 25).
age(carter, 32).
age(wyatt, 27).
age(jayden, 43).
age(john, 45).
age(owen, 21).
age(dylan, 42).
age(luke, 31).
age(emma, 25).
age(olivia, 32).
age(ava, 22).
age(isabella, 24).
age(sophia, 37).
age(mia, 42).
age(charlotte, 25).
age(amelia, 44).
age(evelyn, 25).
age(abigail, 21).
age(harper, 23).
age(emily, 43).
age(elizabeth, 28).
age(avery, 38).
age(sofia, 22).
age(ella, 23).
age(madison, 42).
age(scarlett, 21).
age(victoria, 40).
age(aria, 33).
age(grace, 25).
age(chloe, 41).
age(camila, 39).
age(penelope, 27).
age(riley, 44).
age(layla, 38).
age(lillian, 29).
age(nora, 37).
age(zoey, 40).
age(mila, 22).
personality(liam, 6). 
personality(noah, 3).
personality(william, 3).
personality(james, 9).
personality(logan, 3).
personality(benjamin, 3).
personality(mason, 4).
personality(elijah, 1).
personality(oliver, 4).
personality(jacob, 10).
personality(lucas, 2).
personality(michael, 4).
personality(alexander, 3).
personality(ethan, 3).
personality(daniel, 6).
personality(matthew, 10).
personality(aiden, 8).
personality(henry, 8).
personality(joseph, 10).
personality(jackson, 6).
personality(samuel, 10).
personality(sebastian, 3).
personality(david, 5).
personality(carter, 6).
personality(wyatt, 6).
personality(jayden, 1).
personality(john, 3).
personality(owen, 10).
personality(dylan, 6).
personality(luke, 2).
personality(emma, 8).
personality(olivia, 6).
personality(ava, 2).
personality(isabella, 5).
personality(sophia, 7).
personality(mia, 10).
personality(charlotte, 2).
personality(amelia, 6).
personality(evelyn, 10).
personality(abigail, 7).
personality(harper, 3).
personality(emily, 6).
personality(elizabeth, 1).
personality(avery, 4).
personality(sofia, 10).
personality(ella, 6).
personality(madison, 1).
personality(scarlett, 6).
personality(victoria, 9).
personality(aria, 7).
personality(grace, 2).
personality(chloe, 10).
personality(camila, 5).
personality(penelope, 8).
personality(riley, 8).
personality(layla, 8).
personality(lillian, 1).
personality(nora, 3).
personality(zoey, 4).
personality(mila, 10).
hobbies(liam, video_games).
hobbies(liam, coin_collecting).
hobbies(liam, home_brewing).
hobbies(liam, wood_working).
hobbies(noah, pottery).
hobbies(noah, fishing).
hobbies(noah, calligraphy).
hobbies(noah, cooking).
hobbies(william, antiquing).
hobbies(william, puzzles).
hobbies(william, backpacking).
hobbies(william, sewing).
hobbies(james, knitting).
hobbies(james, pottery).
hobbies(james, cooking).
hobbies(james, puzzles). 
hobbies(logan, origami).
hobbies(logan, baking).
hobbies(logan, cooking).
hobbies(logan, coin_collecting).
hobbies(benjamin, kayaking).
hobbies(benjamin, antiquing).
hobbies(benjamin, sewing).
hobbies(benjamin, stamp_collecting).
hobbies(mason, board_games).
hobbies(mason, home_brewing).
hobbies(mason, stamp_collecting).
hobbies(mason, puzzles). 
hobbies(elijah, knitting).
hobbies(elijah, hunting).
hobbies(elijah, antiquing).
hobbies(elijah, home_brewing).
hobbies(oliver, coin_collecting).
hobbies(oliver, cards).
hobbies(oliver, baking).
hobbies(oliver, chess).
hobbies(jacob, calligraphy).
hobbies(jacob, baking).
hobbies(jacob, stamp_collecting).
hobbies(jacob, antiquing).
hobbies(lucas, calligraphy).
hobbies(lucas, puzzles).
hobbies(lucas, cooking).
hobbies(lucas, knitting).
hobbies(michael, running).
hobbies(michael, mixology).
hobbies(michael, metal_working).
hobbies(michael, coin_collecting).
hobbies(alexander, pool).
hobbies(alexander, wood_working).
hobbies(alexander, kayaking).
hobbies(alexander, mixology).
hobbies(ethan, darts).
hobbies(ethan, coin_collecting).
hobbies(ethan, board_games).
hobbies(ethan, camping).
hobbies(daniel, stamp_collecting).
hobbies(daniel, cooking).
hobbies(daniel, mixology).
hobbies(daniel, coin_collecting).
hobbies(matthew, stamp_collecting).
hobbies(matthew, puzzles).
hobbies(matthew, hiking).
hobbies(matthew, wood_working).
hobbies(aiden, board_games).
hobbies(aiden, origami).
hobbies(aiden, hiking).
hobbies(aiden, camping).
hobbies(henry, puzzles).
hobbies(henry, calligraphy).
hobbies(henry, stamp_collecting).
hobbies(henry, home_brewing).
hobbies(joseph, origami).
hobbies(joseph, hunting).
hobbies(joseph, canoeing).
hobbies(joseph, baking).
hobbies(jackson, backpacking).
hobbies(jackson, antiquing).
hobbies(jackson, canoeing).
hobbies(jackson, pottery).
hobbies(samuel, coin_collecting).
hobbies(samuel, cooking).
hobbies(samuel, board_games).
hobbies(samuel, backpacking).
hobbies(sebastian, cooking).
hobbies(sebastian, antiquing).
hobbies(sebastian, pool).
hobbies(sebastian, camping).
hobbies(david, puzzles).
hobbies(david, canoeing).
hobbies(david, hiking).
hobbies(david, metal_working).
hobbies(carter, mixology).
hobbies(carter, archery).
hobbies(carter, home_brewing).
hobbies(carter, painting).
hobbies(wyatt, photography).
hobbies(wyatt, home_brewing).
hobbies(wyatt, canoeing).
hobbies(wyatt, antiquing).
hobbies(jayden, calligraphy).
hobbies(jayden, photography).
hobbies(jayden, board_games).
hobbies(jayden, pool).
hobbies(john, antiquing).
hobbies(john, chess).
hobbies(john, fishing).
hobbies(john, cards).
hobbies(owen, backpacking).
hobbies(owen, chess).
hobbies(owen, coin_collecting).
hobbies(owen, stamp_collecting).
hobbies(dylan, cards).
hobbies(dylan, canoeing).
hobbies(dylan, kayaking).
hobbies(dylan, metal_working).
hobbies(luke, darts).
hobbies(luke, pool).
hobbies(luke, video_games).
hobbies(luke, board_games).
hobbies(emma, antiquing).
hobbies(emma, canoeing).
hobbies(emma, camping).
hobbies(emma, puzzles).
hobbies(olivia, wood_working).
hobbies(olivia, darts).
hobbies(olivia, antiquing).
hobbies(olivia, video_games).
hobbies(ava, origami).
hobbies(ava, pool).
hobbies(ava, stamp_collecting).
hobbies(ava, coin_collecting).
hobbies(isabella, cooking).
hobbies(isabella, baking).
hobbies(isabella, cards).
hobbies(isabella, video_games).
hobbies(sophia, home_brewing).
hobbies(sophia, puzzles).
hobbies(sophia, metal_working).
hobbies(sophia, board_games).
hobbies(mia, puzzles).
hobbies(mia, camping).
hobbies(mia, photography).
hobbies(mia, archery).
hobbies(charlotte, cooking).
hobbies(charlotte, pool).
hobbies(charlotte, antiquing).
hobbies(charlotte, baking).
hobbies(amelia, canoeing).
hobbies(amelia, drawing).
hobbies(amelia, cooking).
hobbies(amelia, baking).
hobbies(evelyn, wood_working).
hobbies(evelyn, canoeing).
hobbies(evelyn, cooking).
hobbies(evelyn, cards).
hobbies(abigail, knitting).
hobbies(abigail, cooking).
hobbies(abigail, home_brewing).
hobbies(abigail, fishing).
hobbies(harper, darts).
hobbies(harper, cooking).
hobbies(harper, baking).
hobbies(harper, antiquing).
hobbies(emily, canoeing).
hobbies(emily, mixology).
hobbies(emily, home_brewing).
hobbies(emily, baking).
hobbies(elizabeth, antiquing).
hobbies(elizabeth, stamp_collecting).
hobbies(elizabeth, baking).
hobbies(elizabeth, home_brewing).
hobbies(avery, backpacking).
hobbies(avery, fishing).
hobbies(avery, hiking).
hobbies(avery, stamp_collecting).
hobbies(sofia, kayaking).
hobbies(sofia, sewing).
hobbies(sofia, metal_working).
hobbies(sofia, cooking).
hobbies(ella, hunting).
hobbies(ella, knitting).
hobbies(ella, antiquing).
hobbies(ella, photography).
hobbies(madison, running).
hobbies(madison, painting).
hobbies(madison, backpacking).
hobbies(madison, baking).
hobbies(scarlett, kayaking).
hobbies(scarlett, home_brewing).
hobbies(scarlett, chess).
hobbies(scarlett, pool).
hobbies(victoria, backpacking).
hobbies(victoria, board_games).
hobbies(victoria, stamp_collecting).
hobbies(victoria, metal_working).
hobbies(aria, baking).
hobbies(aria, video_games).
hobbies(aria, cooking).
hobbies(aria, wood_working).
hobbies(grace, mixology).
hobbies(grace, hiking).
hobbies(grace, sewing).
hobbies(grace, calligraphy).
hobbies(chloe, running).
hobbies(chloe, stamp_collecting).
hobbies(chloe, coin_collecting).
hobbies(chloe, camping).
hobbies(camila, pottery).
hobbies(camila, home_brewing).
hobbies(camila, coin_collecting).
hobbies(camila, photography).
hobbies(penelope, antiquing).
hobbies(penelope, hiking).
hobbies(penelope, canoeing).
hobbies(penelope, darts).
hobbies(riley, cooking).
hobbies(riley, antiquing).
hobbies(riley, mixology).
hobbies(riley, running).
hobbies(layla, baking).
hobbies(layla, archery).
hobbies(layla, cooking).
hobbies(layla, mixology).
hobbies(lillian, stamp_collecting).
hobbies(lillian, hiking).
hobbies(lillian, origami).
hobbies(lillian, kayaking).
hobbies(nora, baking).
hobbies(nora, home_brewing).
hobbies(nora, fishing).
hobbies(nora, chess).
hobbies(zoey, cooking).
hobbies(zoey, mixology).
hobbies(zoey, stamp_collecting).
hobbies(zoey, backpacking).
hobbies(mila, coin_collecting).
hobbies(mila, cooking).
hobbies(mila, hiking).
hobbies(mila, baking).

match_kinsey(A, B):-kinsey(A, X), kinsey(B, X), X < 3, man(A), woman(B).
match_kinsey(A, B):-kinsey(A, X), kinsey(B, X), X < 3, woman(A), man(B).
match_kinsey(A, B):-A \= B, kinsey(A, X), kinsey(B, X), X > 4, man(A), man(B).
match_kinsey(A, B):-A \= B, kinsey(A, X), kinsey(B, X), X > 4, woman(A), woman(B).
match_age(A, B):-A \= B, age(A, X), age(B, Y), abs(X-Y) < 4.
match_personality(A, B):-A \= B, personality(A, X), personality(B, Y), abs(X-Y) < 4.
match_hobbies(A, B):-A \= B, hobbies(A, X), hobbies(B, Y), X = Y.

fun_date(A, B):-match_kinsey(A, B), match_personality(A, B).
opposites_attract(A, B):-match_kinsey(A, B), not(match_personality(A, B)), not(match_hobbies(A, B)).
perfect_match(A, B):-match_kinsey(A, B), match_age(A, B), match_personality(A, B), match_hobbies(A, B), A \= B.